AllCops:
  Include:
    - Gemfile
    - Rakefile
  Exclude:
    - vendor/*

StringLiterals:
  Enabled: false

LineLength:
  Max: 99

Documentation:
  Enabled: false

Style/TrivialAccessors:
  ExactNameMatch: true
